In [31]:
import os
import matplotlib.pyplot as plt
import joblib
import numpy as np
import pandas as pd
plt.style.use('fivethirtyeight')

In [46]:
class Perceptron:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4
        self.eta = eta # Learning  rate
        self.epochs = epochs # Iterations

    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    

    def activation_function(self, z):
        return np.where(z > 0, 1, 0)#if z is greater than 0 put 1 else put 0


    def fit(self, X, y):
        self.X = X
        self.y = y
    
        X_with_bias = np.c_[self.X, -np.ones((len(self.X),1))]
        print(f'X_with_bias: \n{X_with_bias}')

        for epoch in range(self.epochs):
            print("__"*10)
            print(f'for epoch >> {epoch + 1}')
            print('__'*10)
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)

            print(f'predicted value after the forward pass: \n{y_hat}')

            self.error = self.y - y_hat
            print(f'Error at every step: \n{self.error}')

            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f'updated wioghts after ephoc: {epoch + 1}/{self.epochs}: \n {self.weights}')
            print('##'*10)

    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X),1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)

       

In [26]:
obj = Perceptron(eta=0.01, epochs=10)

In [14]:
obj.eta

0.01

In [15]:
obj.epochs

10

In [16]:
obj.weights

array([ 9.81353770e-05, -3.92539363e-05, -5.42446417e-05])

In [27]:
X = np.ones((4,2))

In [19]:
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
y = np.ones((4,1))

In [21]:
y

array([[1.],
       [1.],
       [1.],
       [1.]])

In [29]:
obj.fit(X,y)

X_with_bias: 
[[ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]
 [ 1.  1. -1.]]


In [34]:
# Lets prepare the data

OR = {
    "x1": [0,0,1,1],
    "x2":[0,1,0,1],
    "y":[0,1,1,1]
}

df_OR = pd.DataFrame(OR)

df_OR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [35]:
def prepare_data(df, target_col="y"):
    X = df.drop(target_col,axis=1)
    y = df[target_col]
    return X, y

In [47]:
X, y = prepare_data(df_OR)

ETA  = 0.1
EPOCHS = 10

model_or = Perceptron(eta=ETA, epochs=EPOCHS)

In [52]:
model_or.fit(X,y)

X_with_bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
____________________
for epoch >> 1
____________________
predicted value after the forward pass: 
[0 1 1 1]
Error at every step: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wioghts after ephoc: 1/10: 
 [0.09986632 0.09982984 0.09979821]
####################
____________________
for epoch >> 2
____________________
predicted value after the forward pass: 
[0 1 1 1]
Error at every step: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wioghts after ephoc: 2/10: 
 [0.09986632 0.09982984 0.09979821]
####################
____________________
for epoch >> 3
____________________
predicted value after the forward pass: 
[0 1 1 1]
Error at every step: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated wioghts after ephoc: 3/10: 
 [0.09986632 0.09982984 0.09979821]
####################
____________________
for epoch >> 4
____________________
predicted value after the forward pass: 
[0 1 1 1

In [50]:
model_or.predict(X)

array([0, 1, 1, 1])

In [51]:
model_or.predict(X=[[1,1]])

array([1])